### ISSUE TITLE
[Meta] Combinators for graph DB

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/Meerkat#28]
- [x] Unified interface for graph-structured data querying: #21 
- [ ] Documentation (github.io): #27
- [ ] Automated release porcess: #30
- [ ] Parallel query processing (single machine, shared memory): #25 
- [ ] Destributed query processing: #24 
- [ ] Conjunctive languages support: #26
